name: e2e test
on: 
  push:
    paths: 
    - '.github/workflows/**'
jobs:
  e2eTests:
    runs-on: ubuntu-latest
    #container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Install & run e2e tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          parallel: false
          start: npx serve
          wait-on: 'http://localhost:5000'
          config-file: cypress.json
          wait-on-timeout: 300
 
